version: '3.4'
services:
  explorer-admin:
    container_name: explorer_admin
    image: "explorer-admin:${TAG:-latest}"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      ETH_ENDPOINT: ${ENDPOINT}
      PROXY_DOMAIN: ${SCHAIN_PROXY_DOMAIN}
      FIRST_SCHAIN_ID: ${FIRST_SCHAIN_ID}
      LAST_SCHAIN_ID: ${LAST_SCHAIN_ID}
      HOST_DIR_PATH: ${HOST_DIR_PATH}
      ETH_API_KEY: ${ETH_API_KEY}
      SCHAIN_NAMES: ${SCHAIN_NAMES}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/skale-explorer/data
    command: "python3 admin/agent.py"
  nginx:
    image: nginx:1.19.6
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d/:ro
      - ./data/certs:/data/