version: '3.4'
services:
  explorer-admin:
    container_name: explorer_admin
    image: "explorer-admin:${TAG:-latest}"
    restart: unless-stopped
    build:
      context: admin
      dockerfile: Dockerfile
    network_mode: host
    environment:
      ETH_ENDPOINT: ${ENDPOINT}
      PROXY_DOMAIN: ${SCHAIN_PROXY_DOMAIN}
      FIRST_SCHAIN_ID: ${FIRST_SCHAIN_ID}
      LAST_SCHAIN_ID: ${LAST_SCHAIN_ID}
      HOST_DIR_PATH: ${HOST_DIR_PATH}
      VERSION: ${VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/skale-explorer/data
      - ./deps:/skale-explorer/deps
  statistics-collector:
    container_name: statistics_collector
    image: "statistics-collector:${TAG:-latest}"
    restart: unless-stopped
    build:
      context: statistics-collector
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./data:/skale-explorer/data
  nginx:
    image: nginx:1.19.6
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certs:/data/